#!/bin/bash
DOCKUTIL=$/usr/local/bin/dockutil
$DOCKUTIL --remove all --allhomes
$DOCKUTIL --add /Applications/Launchpad.app --allhomes
$DOCKUTIL --add /Applications/Managed\ Software\ Center.app --allhomes
$DOCKUTIL --add /Applications/Google\ Chrome.app --allhomes
$DOCKUTIL --add /Applications/System\ Preferences.app --allhomes
$DOCKUTIL --add ~/Downloads --allhomes
exit 0